CREATE DATABASE APIALMOXARIFADO
CREATE TABLE Categoria (
    CATID INT PRIMARY KEY,
    CATNOME VARCHAR(255) NOT NULL
);


CREATE TABLE Produto (
    PRODID INT PRIMARY KEY,
    PRODNOME VARCHAR(255) NOT NULL,
    CATID INT,
    FOREIGN KEY (CATID) REFERENCES Categoria(CATID)
);

CREATE TABLE Departamento (
    DEPID INT PRIMARY KEY,
    DEPNOME VARCHAR(255) NOT NULL
);


CREATE TABLE Funcionario (
    FUNCID INT PRIMARY KEY,
    FUNCNOME VARCHAR(255) NOT NULL,
    DEPID INT,
    FOREIGN KEY (DEPID) REFERENCES Departamento(DEPID)
);


CREATE TABLE CategoriaMotivo (
    CAMID INT PRIMARY KEY,
    CAMDESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE MotivoSaida (
    MOTID INT PRIMARY KEY,
    MOTDESCRICAO VARCHAR(255) NOT NULL,
    CAMID INT,
    FOREIGN KEY (CAMID) REFERENCES CategoriaMotivo(CAMID)
);


INSERT INTO Categoria (CATID, CATNOME) VALUES (1, 'Eletrônicos');

SELECT * FROM Categoria;

UPDATE Categoria SET CATNOME = 'Eletrodomésticos' WHERE CATID = 1;

DELETE FROM Categoria WHERE CATID = 1;


INSERT INTO Produto (PRODID, PRODNOME, CATID) VALUES (1, 'Smartphone', 1);

SELECT * FROM Produto;

UPDATE Produto SET PRODNOME = 'Smartphone Plus' WHERE PRODID = 1;

DELETE FROM Produto WHERE PRODID = 1;




INSERT INTO CategoriaMotivo (CAMID, CAMDESCRICAO) VALUES (1, 'Devolução');

SELECT * FROM CategoriaMotivo;

UPDATE CategoriaMotivo SET CAMDESCRICAO = 'Troca' WHERE CAMID = 1;

DELETE FROM CategoriaMotivo WHERE CAMID = 1;

